server.port: 9199

datasource:
  host: localhost
  username: root
  database: tst_db
  password: Paytm@123


# JWT CREATION
jwtClientId: oereact
jwtSecret: 4YUVqhMHN40NSbP3tUZpHJ4fQM9Nx7rWpCezsuV32Fo=

cipherKey: C0062EACFAA21AF802B4A51B8F917EFD

jwt_token_validity:
  ttl:
    sec: 900
